"""FastAPI serving layer for SEBI RAG Bot.
Endpoints:
  POST /query          - Executes multi-agent RAG / quant workflow
  GET  /health         - Liveness check
  GET  /eval-summary   - RAGAS evaluation metrics report
  GET  /               - Service metadata
"""
import os
import json
from pathlib import Path
from typing import List, Dict, Any, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage

from backend.agents import build_graph

app = FastAPI(
    title="SEBI RAG Bot API",
    description="Compliance and Regulatory Assistant for SEBI, RBI, and DPDPA regulations with Market Volatility intelligence.",
    version="1.0.0"
)

# Enable CORS for Next.js frontend (local dev & production)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Compile agent graph once on startup
graph = build_graph()

class QueryRequest(BaseModel):
    question: str = Field(..., min_length=2, example="What are SEBI's minimum public shareholding requirements?")

class SourceItem(BaseModel):
    source: str
    page: Optional[int] = 1
    text: Optional[str] = ""
    score: Optional[float] = 0.0

class QueryResponse(BaseModel):
    answer: str
    sources: List[Dict[str, Any]] = []
    agent_used: str

@app.get("/")
def root():
    return {
        "service": "SEBI RAG Bot",
        "status": "online",
        "version": "1.0.0",
        "endpoints": ["/health", "/query", "/eval-summary", "/docs"]
    }

@app.get("/health")
def health():
    return {"status": "ok", "version": "1.0.0"}

@app.post("/query", response_model=QueryResponse)
async def query(req: QueryRequest):
    try:
        inputs = {
            "messages": [HumanMessage(content=req.question.strip())],
            "next_agent": "",
            "sources": []
        }
        result = graph.invoke(inputs)

        messages = result.get("messages", [])
        if not messages:
            raise HTTPException(status_code=500, detail="No response generated by agent graph.")

        answer = messages[-1].content
        agent_used = result.get("next_agent", "rag_agent")
        sources = result.get("sources", [])

        return QueryResponse(
            answer=answer,
            sources=sources,
            agent_used=agent_used
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Query execution error: {str(e)}")

@app.get("/eval-summary")
def eval_summary():
    report_path = Path("eval/ragas_report.json")
    if not report_path.exists():
        # Fallback check relative to project root
        project_root = Path(__file__).parent.parent
        report_path = project_root / "eval" / "ragas_report.json"

    if not report_path.exists():
        return {
            "message": "Evaluation report not found. Run 'python scripts/eval_rag.py' to generate metrics.",
            "status": "pending"
        }

    try:
        data = json.loads(report_path.read_text(encoding="utf-8"))
        return data
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error reading eval report: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
